off_scoring_fields = {
    'passing_int'  :  -3,
    'passing_sk'  :  -1,
    'passing_sk_yds'  :  0.2,
    'passing_tds'  :  6,
    'passing_twoptm'  :  2,
    'passing_yds'  :  0.2,
    'receiving_tds'  :  6,
    'receiving_twoptm'  :  2,
    'receiving_yds'  :  0.2,
    'rushing_loss_yds'  :  0.2,
    'rushing_tds'  :  6,
    'rushing_twoptm'  :  2,
    'rushing_yds'  :  0.2,
}

def_scoring_fields = {
    'defense_ffum'  :  1,
    'defense_fgblk'  :  1,
    'defense_frec'  :  3,
    'defense_frec_tds'  :  6,
    'defense_int'  :  3,
    'defense_int_tds'  :  6,
    'defense_misc_tds'  :  6,
    'defense_puntblk'  :  1,
    'defense_safe'  :  2,
    'defense_sk'  :  1,
    'defense_sk_yds'  :  -0.2,
    'defense_tkl_loss_yds'  :  -0.2,
    'defense_xpblk'  :  1,
    'fumbles_forced'  :  1,
    'fumbles_rec_tds'  :  6,
    'fumbles_rec_yds'  :  0.2,
    'kicking_fgb'  :  1,
    'kicking_rec_tds'  :  6,
    'kicking_xpb'  :  1,
    'kickret_tds'  :  6,
    'kickret_yds'  :  0.04,
    'punting_blk'  :  -1,
    'puntret_tds'  :  6,
    'puntret_yds'  :  0.04,
}

kicker_scoring_fields = {
    'kicking_fgm'  :  3,
    'kicking_fgmissed'  :  -1,
    'kicking_xpmade'  :  1,
    'kicking_xpmissed'  :  -1,
}
